import { chromium } from 'file:///C:/Users/Admin/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const root='C:/Users/Admin/mbca/TP2-3/data/interim/team_final_20260911';
const read=(name)=>JSON.parse(fs.readFileSync(`${root}/${name}.json`,'utf8'));
const catalog=read('catalog_api');
const audit=read('readiness_api');
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[];
page.on('pageerror',error=>errors.push(error.message));
await page.route('**/ai/**',async route=>{
  const request=route.request();
  if(request.method()!=='GET')return route.abort();
  const path=new URL(request.url()).pathname;
  if(path.endsWith('/regions/catalog'))return route.fulfill({json:catalog});
  if(path.endsWith('/regions/readiness-audit'))return route.fulfill({json:audit});
  const match=path.match(/\/demo\/(\d+)\/dashboard$/);
  if(match)return route.fulfill({json:read(`dashboard_${match[1]}`)});
  const freshness=path.match(/\/demo\/(\d+)\/generation-readiness$/);
  if(freshness)return route.fulfill({json:read(`generation_readiness_${freshness[1]}`)});
  return route.fulfill({json:{}});
});
await page.goto('http://127.0.0.1:5180/planning');
const select=page.locator('.work-region-picker select');
await page.waitForFunction(()=>document.querySelectorAll('.work-region-picker option').length===250);
assert.equal(await select.locator('option').count(),catalog.total_count);
await select.selectOption('30200');
await page.getByRole('heading',{name:'대전광역시 유성구',exact:true}).waitFor();
await page.waitForFunction(()=>{const button=document.querySelector('.planning-summary-generate');return button && !button.disabled;});
assert.equal(await page.getByText('데이터 업데이트 필요',{exact:true}).count(),0);
assert.equal(await select.inputValue(),'30200');
assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('tour-insight-selected-region')).code),'30200');
const hasHorizontalOverflow=await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth);
assert.equal(hasHorizontalOverflow,false);
await page.screenshot({path:`${root}/planning_250_regions.png`,fullPage:true});
assert.deepEqual(errors,[]);
fs.writeFileSync(`${root}/browser_check.json`,JSON.stringify({status:'passed',catalog_options:250,selected_region:'30200',page_errors:errors,source:'actual API payload replay; generation POST blocked',local_models_ready:audit.local_models_ready},null,2));
console.log('PASS: 250 catalog regions; new region selection; actual payload replay; no generation calls');
await browser.close();
