import fs from 'node:fs/promises';
import {chromium} from 'file:///C:/Users/Admin/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
const dir='C:/Users/Admin/mbca/TP2-3/storage/previews/presentation_revision';
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
const page=await browser.newPage({viewport:{width:1920,height:4000},deviceScaleFactor:1.5});
await page.goto('http://localhost:5176/ml-test',{waitUntil:'domcontentloaded'});
const card=page.locator('.ml-module-card').first();await card.waitFor({timeout:180000});await page.evaluate(()=>window.scrollTo(0,0));await page.waitForTimeout(2000);
const bounds=await card.evaluate(e=>{let a=e.getBoundingClientRect(),b=e.querySelector('.ml-module-main').getBoundingClientRect();return {x:a.x,y:a.y,width:a.width,height:b.bottom-a.top};});
await page.screenshot({path:dir+'/ml_detail.png',clip:bounds});
await page.goto('http://localhost:5176/openai-test',{waitUntil:'domcontentloaded'});await page.locator('.openai-agent-map').waitFor();
await page.waitForTimeout(1200);
const agentBounds=await page.locator('.openai-agent-map').evaluate(e=>{const a=e.getBoundingClientRect(),b=e.querySelector('.agent-output').getBoundingClientRect();return {x:a.x,y:a.y,width:a.width,height:b.bottom-a.top+12};});
await page.screenshot({path:dir+'/agent_flow.png',clip:agentBounds});
await browser.close();console.log('ML focus complete');
